### ISSUE TITLE
Cache is empty and KRB5CCNAME is absent in my environment

### ISSUE THREAD

**Issue by chance-comer** [gssapi/mod_auth_gssapi#222]
I have both GssapiDelegCcacheDir and GssapiCredStore are empty. There is no KRB5CCNAME in the list of environment variables.

About my settings:

OS Debian Buster
Apache 2.4.38 
PHP 7.3.14-1~deb10u1. 

I installed mod_auth_GSSAPI. 
Server config is:
```
<Directory /mydirectory>
     AuthType GSSAPI
     AuthName "Active Directory"
     GssapiCredStore keytab:/etc/krb5.keytab
     GssapiCredStore ccache:var/tmp/krb5cache
     GssapiDelegCcacheDir /var/tmp/krb5deleg
     GssapiDelegCcacheUnique On
     require valid-user
</Directory>
```
Apache username is www-data.

Rights for krb5.conf
```
getfacl etc/krb5.conf
# file: etc/krb5.conf
# owner: root
# group: root
user::rw-
user:www-data:r--
group::r--
mask::r--
other::r--
```
Rights for krb5.keytab
```
getfacl etc/krb5.keytab
# file: etc/krb5.keytab
# owner: root
# group: root
user::rw-
user:www-data:r--
group::---
mask::r--
other::---
```
Rights for /var/
```
ls -l /var/
drwxrwxrwt  5 root root  4096 июл 30 11:09 tmp
```
Rights for /var/tmp/krb5cache and /var/tmp/krb5deleg
```
getfacl var/tmp/krb5deleg
# file: var/tmp/krb5deleg
# owner: root
# group: root
user::rwx
user:www-data:rwx
group::r-x
mask::rwx
other::r-x
```
From my krb5.conf
```
[libdefaults]
        default_realm = DOMAIN.RU
        dns_lookup_realm = true
        dns_lookup_kdc = true
        forwardable = true
        ticket_lifetime = 10h
        renew_lifetime = 4d


# The following krb5.conf variables are only for MIT Kerberos.
        kdc_timesync = 1
        ccache_type = 4
        forwardable = true
        proxiable = true
```

Authentication working fine, I can get access to the site. Defined login name is correct.
But I want use KRB5CCNAME in PHP code to get access to LDAP server. KRB5CCNAME is absent. 
Folders /var/tmp/krb5cache and /var/tmp/krb5deleg are always empty.

**Comment by simo5** [comment]
Hi, a few comments on this:

1. The GssapiCredStore option just tells the GSSAPI library where a ccache would be if one was present, but no ccache is needed to verify incoming tickets, so you should not expect one to be generated.
2. The GssapiDelegCcacheDir options tells mod_auth_gssapi where to store credentials *if* the client delegates them to the server. In general clients tend *not to* delegate credentials because delegating TGTs is basically giving away your identity. So I would not expect credentials to be normally delegated to a server and therefore nothing to be generated.
3. A ccache is only needed if you want to impersonate the user to do some operation on their behalf.

So if you are indeed in need to perform operations on behalf of a user you actually have 2 options.

1. Configure clients for delegation. This is cumbersome and makes your server a security target, because you are collecting credentials for all your users, credentials that can be used almost unbounded.
2. Look into constrained delegation and how it works. If you want to know what constrained delegation is look at this blog post I issued a while ago: http://ssimo.org/blog/id_011.html

If you want to do (1) then you need to look into the *client's* configuration and potentially support in your client application (most defer to default krb5.conf configuration and do not interfere).

If you are interested in (2) then mod_auth_gssapi can help you by performing "the first half" of it.
To do that look at the GssapiUseS4U2Proxy. When set it will generate credentials in GssapiDelegCcacheDir that can be used to impersonate users. However keep in mind that this requires collaboration (and configuration) of the KDC, so you need to understand how to activate it in your environment. (it is different between AD vs something like FreeIPA or a classic standalone KDC).

These are the nuts & bolts, so I'll close this issue,
but feel free to comment or ask for further clarification on this issue if needed.
